spring.application.name=Registro

# Base de datos principal (usuarios)
spring.data.mongodb.uri=mongodb://localhost:27017/RegistroUser

# Base de datos activos
sigma.mongodb.uri=mongodb://localhost:27017/sigma_activos